### ISSUE TITLE
SSP creative review needs to support per-publisher restrictions

### ISSUE THREAD

**Issue by brodrigu** [AdRoll/TERN#2]
The solution proposed for advanced creative review is elegant but does not support the level of granularity needed to meet publisher review requirements.

Imagine an advertisement for fun new restaurant with a creative that exclaims "Celebrate with us!". news-publisher.nyc may feel this ad is appropriate for the nightlife section of their website, but not the obituaries section. Likewise, you can imagine a creative that might be fine on any news-publisher.nyc page but not any kids-corner.fun page. Sometimes the publisher may simply not like the esthetics of the creative and disapprove for subjective reasons.

The free-form "category" described in the proposal could theoretically be extended to support very granular categories that approach the number of domains or even pages on the internet, and be used to list approved publishers or pages, but the SSP would need to be able to inject its own categories for this to be feasible. 

However, this approach may require more frequent refreshes between the browser and the SSP as more publishers would approve a given creative over time, unlocking additional qualified inventory.

**Comment by appascoe** [comment]
Hey, @brodrigu . Thanks for the feedback!

Sorry I didn't notice this right away, as the official TERN doc got merged into the TURTLEDOVE WICG repository. I need to update here to point to the new location.

Let me ruminate on this a bit; I may be able to come up with a solution.

**Comment by appascoe** [comment]
Hey, @brodrigu .

We believe we have a resolution to this issue in our PR [here](https://github.com/WICG/turtledove/pull/58). It's a large PR, but it creates a mechanism through which SSPs can supply their own categories for ads, and it also includes an FAQ item that discusses how to accomplish publisher brand safety.
